### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by xianglong111** [DrawAChicken/Easy-Electron#1]
npm run dev之后出现 
404s will fallback to /index.html
(node:11624) DeprecationWarning: loaderUtils.parseQuery() received a non-string
value which can be problematic, see https://github.com/webpack/loader-utils/issu
es/56
parseQuery() will be replaced with getOptions() in the next major version of loa
der-utils.
请问是什么原因？

**Comment by DrawAChicken** [comment]
这种情况已经运行了
浏览器访问http://localhost:8080/resource/#/
或者electron运行后就可以看到
